name: uni_links_nfc_support_platform_interface
description: The platform interface for the uni_links_nfc_support plugin.
version: 1.0.0
homepage: https://github.com/doch2/uni_links_nfc_support/tree/master/uni_links_nfc_support_platform_interface

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"