name: uni_links_nfc_support_web
description: A web implementation of the Uni Links platform interface.
version: 0.1.2
homepage: https://github.com/doch2/uni_links_nfc_support/tree/main/uni_links_nfc_support_web

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  uni_links_nfc_support_platform_interface: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: UniLinksPlugin
        fileName: 'uni_links_nfc_support_web.dart'
